### ISSUE TITLE
Protection on lack of entitlement

### ISSUE THREAD

**Issue by JezzaInSingapore** [SymphonyPlatformSolutions/symphony-decision-tree-bot#4]
Could you please update RoomListenerImpl.java as attached.

This adds protection for the scenario in which a user does not have attachment rights.
[RoomListenerImpl.java.gz](https://github.com/SymphonyPlatformSolutions/symphony-decision-tree-bot/files/5508218/RoomListenerImpl.java.gz)

**Comment by ystxn** [comment]
Merged in PR #5
